services:
  - type: web
    name: swing-trading-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "python main_pipeline.py && streamlit run dashboard.py --server.port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12